# Do **not** use this yml for production. It is not up-to-date.
# Use https://docs.postiz.com/installation/docker-compose
# This is only for the dev enviroment

services:
  pozmixal-postgres:
    # ref: https://hub.docker.com/_/postgres
    image: postgres:17-alpine # 17.0
    container_name: pozmixal-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pozmixal-local-pwd
      POSTGRES_USER: pozmixal-local
      POSTGRES_DB: pozmixal-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pozmixal-network

  pozmixal-redis:
    # ref: https://hub.docker.com/_/redis
    image: redis:7-alpine # 7.4.0
    container_name: pozmixal-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - pozmixal-network

  pozmixal-pg-admin:
    # ref: https://hub.docker.com/r/dpage/pgadmin4/tags
    image: dpage/pgadmin4:latest
    container_name: pozmixal-pg-admin
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pozmixal-network

  pozmixal-redisinsight:
    # ref: https://hub.docker.com/r/redis/redisinsight
    image: redis/redisinsight:latest
    container_name: pozmixal-redisinsight
    links:
      - pozmixal-redis
    ports:
      - '5540:5540'
    volumes:
      - redisinsight:/data
    networks:
      - pozmixal-network
    restart: always

volumes:
  redisinsight:
  postgres-volume:
    external: false

networks:
  pozmixal-network:
    external: false
